inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '*.gemspec'
    - 'spec/dummy-*/**/*'

Lint/EndAlignment:
  AlignWith: variable

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  MaxLineLength: 40

Style/IndentHash:
  EnforcedStyle: consistent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
