language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
script: "bundle exec rspec"
before_install:
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
