language: ruby
rvm:
  - 1.9.3
  - '2.2'
  - jruby-19mode
env:
  - RAILS_VERSION='~> 2.3.0'
  # - RAILS_VERSION='~> 3.0.0' # conflicting adapters for postgresql and mysql2
  - RAILS_VERSION='~> 3.1.0'
  - RAILS_VERSION='~> 3.2.0'
  - RAILS_VERSION='~> 4.0.0'
  - RAILS_VERSION='~> 4.1.0'
  - RAILS_VERSION='~> 4.2.0'
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; else
    bundle exec rspec
  ; fi
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
matrix:
  fast_finish: true
  include:
    - {rvm: 1.8.7, env: RAILS_VERSION='~> 2.3.0'}
    - {rvm: 1.8.7, env: RAILS_VERSION='~> 3.2.0'}

    - {rvm: '2.0', env: RAILS_VERSION='~> 2.3.0'}
    - {rvm: '2.0', env: RAILS_VERSION='~> 3.2.0'}
    - {rvm: '2.0', env: RAILS_VERSION='~> 4.2.0'}

    - {rvm: '2.1', env: RAILS_VERSION='~> 2.3.0'}
    - {rvm: '2.1', env: RAILS_VERSION='~> 3.2.0'}
    - {rvm: '2.1', env: RAILS_VERSION='~> 4.2.0'}

    - {env: RUBOCOP=true, rvm: default}
  allow_failures:
    - rvm: jruby-19mode
