language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ree
env:
  - RAILS_VERSION='~> 2.3.0'
  # - RAILS_VERSION='~> 3.0.0' # conflicting adapters for postgresql and mysql2
  - RAILS_VERSION='~> 3.1.0'
  - RAILS_VERSION='~> 3.2.0'
  - RAILS_VERSION='~> 4.0.0'
script: "bundle exec rspec"
before_install:
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
  exclude:
    - rvm: 1.8.7 # not supported by rails 4
      env: RAILS_VERSION='~> 4.0.0'
    - rvm: ree # not supported by rails 4
      env: RAILS_VERSION='~> 4.0.0'
    - rvm: 2.0.0 # problems with iconv
      env: RAILS_VERSION='~> 2.3.0'
