language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
env:
  - RAILS_VERSION='~> 2.3.0'
  - RAILS_VERSION='~> 3.0.0'
  - RAILS_VERSION='~> 3.1.0'
  - RAILS_VERSION='~> 3.2.0'
  - RAILS_VERSION='~> 4.0.0'
script: "bundle exec rspec"
before_install:
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
matrix:
  allow_failures:
    - jruby-18mode
    - jruby-19mode
    - rbx-18mode
    - rbx-19mode
